# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.12-slim
WORKDIR /app
# Copy project files
COPY pyproject.toml uv.lock README.md ./
COPY src ./src
# Install dependencies and package
RUN pip install --no-cache-dir .
# Ensure logging flushes immediately
ENV PYTHONUNBUFFERED=1
ENTRYPOINT ["spotify-mcp"]
